cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
# Configuração de download e upload (multipart)
file:
  upload-dir: /Users/pedro/ProtejtoSpringBoot/rest-with-springBoot-and-java-erudio/Curso/uploadDir
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rest-with-spring-boot-erudio.cvfwx45o5i3m.us-east-1.rds.amazonaws.com:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
# Configuração de download e upload (multipart)
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch:
  - /api/**/v1/**
  - /auth/**
  swagger-ui:
    use-root-path: true